-- File Name: Magnitude Analysis
-- Description: Explore various dimensions of the business by analyzing customer, product, and revenue data.

-- --------------------------------------------------------------------------------
-- QUESTIONS TO BE ANSWERED:
-- 01. Find total customers by countries
-- 02. Find total customers by gender
-- 03. Find total products by category
-- 04. What is the average cost in each category?
-- 05. What is the total revenue generated for each category?
-- 06. Find total revenue generated by each customer
-- 07. What is the distribution of sold items across countries?
-- --------------------------------------------------------------------------------


-- 01. Find total customers by countries
SELECT 
    country, 
    COUNT(customer_id) AS Number_Of_Customers 
FROM dim_customers 
GROUP BY country;
#result:
-- 'Australia','3591'
-- 'United States','7482'
-- 'Canada','1571'
-- 'Germany','1780'
-- 'United Kingdom','1913'
-- 'France','1810'
-- 'n/a','337'


-- 02. Find total customers by gender
SELECT 
    gender, 
    COUNT(customer_id) AS Number_Of_Customers 
FROM dim_customers 
GROUP BY gender;
#result:-- 
-- 'Male','9341'
-- 'Female','9128'
-- 'n/a','15'


-- 03. Find total products by category
SELECT 
    category, 
    COUNT(DISTINCT product_name) AS Number_Of_Products 
FROM dim_products 
GROUP BY category;

-- result:
-- '','7'
-- 'Accessories','29'
-- 'Bikes','97'
-- 'Clothing','35'
-- 'Components','127'

-- 04. What is the average cost in each category?
SELECT 
    category, 
    AVG(cost) AS Average_Cost 
FROM dim_products 
GROUP BY category;
-- result:
-- 'Components','264.7165'
-- 'Bikes','949.4433'
-- 'Clothing','24.8000'
-- 'Accessories','13.1724'
-- '','28.5714'


-- 05. What is the total revenue generated for each category?
SELECT 
    dp.category AS Category, 
    SUM(fs.sales_amount) AS Revenue
FROM fact_sales fs
JOIN dim_products dp 
    ON fs.product_key = dp.product_key
GROUP BY dp.category;
-- result:
-- 'Accessories','699909'
-- 'Clothing','339692'
-- 'Bikes','28311657'

-- 06. Find total revenue generated by each customer
SELECT 
    dc.first_name AS Customer, 
    SUM(fs.sales_amount) AS Revenue
FROM fact_sales fs
JOIN dim_customers dc 
    ON fs.customer_key = dc.customer_key
GROUP BY dc.first_name order by  Revenue desc limit 10 ;
-- result:'Morgan','145034'
-- 'Ian','138310'
-- 'Jennifer','134920'
-- 'Kaitlyn','132193'
-- 'Chloe','132068'
-- 'Isabella','128436'
-- 'Eduardo','127569'
-- 'Seth','125757'
-- 'Abigail','125449'
-- 'Dalton','124604'


-- 07. What is the distribution of sold items across countries?
SELECT 
    dc.country AS Country, 
    SUM(fs.sales_amount) AS Revenue
FROM fact_sales fs
JOIN dim_customers dc 
    ON fs.customer_key = dc.customer_key
GROUP BY dc.country;
-- result:'United States','9162225'
-- 'Germany','2894066'
-- 'United Kingdom','3389046'
-- 'France','2641223'
-- 'Canada','1977733'
-- 'Australia','9060145'
-- 'n/a','226820'


-- --------------------------------------------------------------------------------
-- Data Preview (Optional: For Reference Only)
-- --------------------------------------------------------------------------------

SELECT * FROM dim_customers;
SELECT * FROM fact_sales;
SELECT * FROM dim_products;



# 📊 Magnitude Analysis – Strategic Business Insights

> **File Description**: This document summarizes the key insights derived from SQL queries performed on customer, product, and sales data. These insights help identify strategic opportunities and performance highlights across product lines and geographic markets.

---

-- Key Business Insights 

-- United States & Australia: Revenue Twins but Not Customer Twins

--   - United States: 7482 customers → ~$9.16M revenue  
--   - Australia: 3591 customers → ~$9.06M revenue

-- ---

-- Gender Balance: A Golden Opportunity
-- - Male: 9341 | Female: 9128 | n/a: 15

-- ---

-- Product Category Focus: Components Are Diverse, Bikes Are Dominant

--   - Components: 127 products → Moderate revenue  
--   - Bikes: 97 products → $28.3M revenue  


-- ---

-- Clothing & Accessories: Underleveraged Upsell Products
-- Low average costs but very low revenue contribution
--   - Clothing Avg. Cost: $24.80 → $339K revenue
--   - Accessories Avg. Cost: $13.17 → $699K revenue


-- ---

-- Revenue Concentration: The 80/20 Rule in Effect
-- Top 10 customers generate over $1.3M+


-- ---

-- Data Hygiene Alert: Beware of the 'n/a' Zones

--   - 337 customers with no country
--   - 15 customers with no gender
--   - 7 products with no category


-- ---

--  Mid-Tier Market Potential: Germany & UK

--   - Germany: $2.89M
--   - UK: $3.38M

-- ---

-- Strategic Summary

-- The data suggests that:
-- - **High-value markets (Australia, Bikes)** should be prioritized.
-- - **Underperforming categories (Clothing, Accessories)** can be repositioned as upsell opportunities.
-- - **Customer segmentation and data hygiene** are critical for unlocking full business potential.

-- ---

